categories:
- Rec General Conversations
conversations:
- - what is your college name
  - My college name is Rajalakshmi Engineering college
- - When was the college founded
  - The college was founded in the year 1997 by Mr. Meganathan
- - How many programs are being offered in college
  - There are totally 12 under graduate programs and 10 post graduate programs offered in the college.
- - How many students are being taken in annually
  - There are totally 1950 students joining every year
- - How many programs are accredited
  - There are totally 9 programs accredited by NAAC
  


